# Generated by Django 3.0.8 on 2020-08-16 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sessions', '0001_initial'),
        ('tournament', '0003_auto_20200816_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='sessions.Session'),
            preserve_default=False,
        ),
    ]
