# Generated by Django 3.0.8 on 2020-08-22 10:46

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('tournament', '0003_auto_20200822_0341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
