# Generated by Django 3.0.8 on 2020-08-22 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20200822_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='tournament.Round'),
        ),
    ]
