# Generated by Django 3.0.8 on 2020-08-16 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20200816_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='password',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
