# Generated by Django 3.0.8 on 2020-08-17 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_auto_20200816_1643'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TournamentPhoto',
            new_name='TournamentEntry',
        ),
        migrations.AddField(
            model_name='battle',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.Game'),
        ),
        migrations.AddField(
            model_name='game',
            name='curr_battle',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='curr_round',
            field=models.IntegerField(choices=[(2, 'TWO'), (4, 'FOUR'), (8, 'EIGHT'), (16, 'SIXTEEN'), (32, 'THIRTYTWO'), (64, 'SIXTYFOUR')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='entries',
            field=models.ManyToManyField(to='tournament.TournamentEntry'),
        ),
        migrations.AddField(
            model_name='game',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.Tournament'),
        ),
        migrations.AlterField(
            model_name='game',
            name='bracket_size',
            field=models.IntegerField(choices=[(2, 'TWO'), (4, 'FOUR'), (8, 'EIGHT'), (16, 'SIXTEEN'), (32, 'THIRTYTWO'), (64, 'SIXTYFOUR')]),
        ),
    ]
