# Generated by Django 3.0.8 on 2020-08-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_auto_20200823_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='num_plays',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamententry',
            name='num_battles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamententry',
            name='num_battlewins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamententry',
            name='num_gamewins',
            field=models.IntegerField(default=0),
        ),
    ]
