# Generated by Django 3.0.8 on 2020-08-18 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_auto_20200817_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='game',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='is_determined',
        ),
        migrations.RemoveField(
            model_name='battle',
            name='size',
        ),
        migrations.RemoveField(
            model_name='game',
            name='entries',
        ),
        migrations.AddField(
            model_name='battle',
            name='entries',
            field=models.ManyToManyField(to='tournament.TournamentEntry'),
        ),
        migrations.AddField(
            model_name='battle',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='tournament.TournamentEntry'),
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_num', models.IntegerField(choices=[(2, 'TWO'), (4, 'FOUR'), (8, 'EIGHT'), (16, 'SIXTEEN'), (32, 'THIRTYTWO'), (64, 'SIXTYFOUR')])),
                ('entries', models.ManyToManyField(to='tournament.TournamentEntry')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.Game')),
            ],
        ),
        migrations.AddField(
            model_name='battle',
            name='round',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tournament.Round'),
            preserve_default=False,
        ),
    ]
