# Generated by Django 3.0.8 on 2020-08-18 20:43

from django.db import migrations, models
import tournament.models.tournament


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_game_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='avatar',
            field=models.FileField(default='', upload_to=tournament.models.tournament.tournament_avatar_directory),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='bracket_size',
            field=models.IntegerField(choices=[(1, 'ONE'), (2, 'TWO'), (4, 'FOUR'), (8, 'EIGHT'), (16, 'SIXTEEN'), (32, 'THIRTYTWO'), (64, 'SIXTYFOUR')]),
        ),
        migrations.AlterField(
            model_name='game',
            name='curr_round',
            field=models.IntegerField(choices=[(1, 'ONE'), (2, 'TWO'), (4, 'FOUR'), (8, 'EIGHT'), (16, 'SIXTEEN'), (32, 'THIRTYTWO'), (64, 'SIXTYFOUR')]),
        ),
        migrations.AlterField(
            model_name='round',
            name='round_num',
            field=models.IntegerField(choices=[(1, 'ONE'), (2, 'TWO'), (4, 'FOUR'), (8, 'EIGHT'), (16, 'SIXTEEN'), (32, 'THIRTYTWO'), (64, 'SIXTYFOUR')]),
        ),
    ]
