# Generated by Django 3.0.8 on 2020-08-21 07:06

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('tournament', '0011_game_is_gameend'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
